api_platform:
    resource: .
    type: api_platform
    prefix: /api/v1
app_swagger_ui:
    path: /api/documentation
    methods: GET
    defaults: { _controller: api_platform.swagger.action.ui, area: default }
api_login_check:
    path: /login
    methods: ['POST']
